spring:
    application:
        name: irori-bank-josef

    datasource:
        url: jdbc:postgresql://localhost:5432/iroribank
        username: josefhabil
        password: ""

    jpa:
        hibernate:
            ddl-auto: update
